### ISSUE TITLE
eSudo does not accept special characters

### ISSUE THREAD

**Issue by JeffHoogland** [JeffHoogland/esudo#2]
esudo prohibits, at the very least, characters from the set "!@#$%^&*()".

Likely due to how python handles strings. Will need to look into a proper fix at some point.

**Comment by rbtylee** [comment]
Commit 2b74f59  address this issue and hopefully fixes it. It works with all broken passwords I know about. I will have it tested on the forums to see if this fixes the problem for those Bodhi users that previously had broken passwords using esudo. If it passes the 'forum test' we can eventually close this issue...
