### ISSUE TITLE
 If the locale is not English, the application will not run

### ISSUE THREAD

**Issue by fu-sen** [JeffHoogland/esudo#5]
esudo when locale ran not english, the esudo window will be displayed,
but the application will not start after the authentication.

For example, this will not start synaptic (locale is not english):
`esudo synaptic`

But this will start up synaptic:
`LANG=C esudo synaptic`

reference:
http://forums.bodhilinux.com/index.php?/topic/14000-translation-issues/

**Comment by rbtylee** [comment]
Confirmed but unsure if this is an esudo issue or an EFL one or Moksha. 

But In this case LANG = "ja_JP.UTF-8" and applications appears to be running but not visible. I haven't saw that with other locales, for example in my test french worked fine.

**Comment by rbtylee** [comment]
This is not an esudo issue. I confirmed this by installing esudo on enlightenment 21.4 with  efl 18.3, and python-efl 1.18 and LANG=ja_JP.UTF-8. On e21 esudo works correctly with LANG = ja_JP.UTF-8, and  the application IS displayed correctly. Therefore, I am closing this issue for esudo.

**Comment by rbtylee** [comment]
I have been re-examining this issue and while it may have worked correctly in e21 or greater, perhaps it was a bug in esudo code. My last commit 747467c hopefully fixes it ...

**Comment by fu-sen** [comment]
I received a report and reinstalled Bodhi Linux 4.1.0.
My Bodhi does not encounter a problem and is currently used normally. 
I will review a few days and add comments if I encounter a problem.

**Comment by fu-sen** [comment]
Immediately after that, I was able to reproduce the problem.
I do not encounter that problem if I switch language of Moksha.
but after using the Ubuntu package "language-selector-gnome" (Language Support),
I encounter that problem.
It is effective for language setting of many applications and system language.

**Comment by fu-sen** [comment]
I noticed that I can rewrite it directly from the source code being Python.
So, I changed /usr/lib/python2.7/dist-packages/esudo/esudo.py .
As a result, it will work normally!
