### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by fredweb69** [JeffHoogland/esudo#6]
Hi guys, I can't use esudo anymore.

root@Ghost:/home/desenvolvedor# gufw
Traceback (most recent call last):
  File "/usr/bin/pkexec", line 5, in <module>
    import esudo.esudo as esudo
  File "/usr/lib/python2.7/dist-packages/esudo/esudo.py", line 15, in <module>
    from efl import evas
ImportError: /usr/lib/python2.7/dist-packages/efl/evas.so: undefined symbol: evas_object_paragraph_direction_set

Whats can I do to fix it?

Best regards.

**Comment by rbtylee** [comment]
We need more details on this. What operating system? How was efl and python-efl installed? What version of elf and python-efl was installed? Did esudo work previously? If so what did you do that 'broke' it?

**Comment by fredweb69** [comment]
Ubuntu 14.04, was working but stop. 
both are instaled.

Package: efl
Status: install ok installed
Priority: extra
Section: unknown
Installed-Size: 18796
Maintainer: Eric W. Brown
Architecture: amd64
Version: 20150806bodhi1.15.0-1
Replaces: ecore, edje, eet, eeze, efreet, eina, eio, embryo, emotion, eobj, ephysics, ethumb, evas
Provides: ecore, edje, eet, eeze, efreet, eina, eio, embryo, emotion, eobj, ephysics, ethumb, evas
Depends: libbulletcollision2.81, libbulletdynamics2.81, libbulletsoftbody2.81, libc6 (>= 2.15), libdbus-1-3 (>= 1.1.1), libfontconfig1 (>= 2.9.0), libfreetype6 (>= 2.2.1), libfribidi0 (>= 0.19.2), libgcc1 (>= 1:4.1.1), libgif4 (>= 4.1.4), libgl1-mesa-glx | libgl1, libglib2.0-0 (>= 2.37.3), libgstreamer-plugins-base1.0-0 (>= 1.0.0), libgstreamer1.0-0 (>= 1.0.0), libharfbuzz0b (>= 0.9.4), libjpeg8 (>= 8c), liblinearmath2.81, libluajit-5.1-2, libmount1 (>= 2.20.1), libpng12-0 (>= 1.2.13-4), libpulse0 (>= 1:0.99.1), libsndfile1 (>= 1.0.20), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.4.2), libtiff5 (>= 4.0.3), libudev1 (>= 199), libx11-6 (>= 2:1.2.99.901), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6 (>= 2:1.2.99.4), libxinerama1, libxp6, libxrandr2 (>= 2:1.2.99.3), libxrender1, libxss1, libxtst6, zlib1g (>= 1:1.1.4)
Conflicts: ecore, edje, eet, eeze, efreet, eina, eio, embryo, emotion, eobj, ephysics, ethumb, evas
Description: EFLs
 Enlightenment Foundation Libraries
---------------
Package: python-efl
Status: install ok installed
Priority: extra
Section: unknown
Installed-Size: 8798
Maintainer: Eric W. Brown
Architecture: amd64
Version: 201612041.18.0bodhi1-1
Replaces: python-ecore, python-edbus, python-edje, python-elementary, python-emotion, python-epdf, python-ethumb, python-evas
Provides: python-ecore, python-edbus, python-edje, python-elementary, python-emotion, python-epdf, python-ethumb, python-evas
Depends: python (>= 2.7), python (<< 2.8)
Conflicts: python-ecore, python-edbus, python-edje, python-elementary, python-emotion, python-epdf, python-ethumb, python-evas
Description: Python EFLs
 Python bindings for the EFLs


Thanks for Your help.

Best regards.

**Comment by rbtylee** [comment]
Is this installed on Bodhi3.x? 

There is a version mismatch of efl and python-efl. If this is Bodhi 3.x downgrade python-efl back to python-efl_20150806bodhi1.15.0.

**Comment by rbtylee** [comment]
I am closing this issue since this is a not an issue with esudo.
